spring:
  datasource:
    url: jdbc:mysql://192.168.118.131:3306/it_student?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1 FROM DUAL
    time-between-eviction-runs-millis: 300000
    min-evictable-idle-time-millis: 1800000
  redis:
    database: 0
    host: 192.168.118.131
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
  #缓存配置读取
  cache:
    type: ehcache
    ehcache:
      config: classpath:app1_ehcache.xml
  #开启cglib动态代理
  aop:
    auto: true
  #kafka配置读取
  kafka:
    bootstrap-servers: 192.168.118.128:9092,192.168.118.129:9092,192.168.118.130:9092
    producer:
      key-serializer:  org.apache.kafka.common.serialization.StringSerializer
      value-serializer:  org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#######rabbitmq
#  rabbitmq:
#    addresses: 192.168.220.131
#    port: 5672
#    username: admin
#    password: admin
#    ##一个虚拟主机持有一组交换机,队列和绑定，用户只能在虚拟主机这个粒度上进行权限控制
#    virtual-host: my_vhost
#####elasticsearch配置读取
#  data:
#    elasticsearch:
#      cluster-name: myes
#      cluster-nodes: 192.168.220.128:9300
#      repositories:
#        enabled: true
#  main:
#    allow-bean-definition-overriding: true
#mybatis相关
#####apollo相关
#app:
#  id: SpringBootDemo
#apollo:
#  meta: ${APOLLO_CONFIG_SERVICE_URL:http://192.168.118.128:8080}
mybatis:
  type-aliases-package: com.itstudent.springbootdemo.model.**
  mapper-locations: classpath:mapper/*.xml